server:
  port: 11023

spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650
      threads:
        io: 2
        listener: 2
    admin:
      service-url: http://localhost:8080
    #      service-url: pulsar://127.0.0.1:6650
    listener:
      concurrency: 5
      schemaType: JSON
pulsar:
  #  service-url: pulsar://hadoop103:6650
  service-url: pulsar://127.0.0.1:6650
  listener-threads: 10
  io-threads: 10
#  consumer:
#    thread-pool-size: 10 # 设置消费者线程池大小
#  tenant: public


