server:
  port: 24212
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8

spring:
  ai:
    mcp:
      client:
        type: async
        name: b42-12-mcp-client
        version: 1.0.0
        request-timeout: 20s
        toolcallback:
          enabled: true
        sse:
          connections:
            mcp-server1:
             url: http://localhost:24211/
    dashscope:
      #      base-url: https://dashscope.aliyuncs.com/api/v1
      #      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${aliQwen-api}
      chat:
        options:
          model: qwen-plus
      # 推理模型
      embedding:
        options:
          model: text-embedding-v3

