server:
  port: 24205
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  data:
    redis:
      host: localhost
      port: 16379
      database: 12
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3.5:4b
    dashscope:
      ##      base-url: https://dashscope.aliyuncs.com/api/v1
      ##      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${aliQwen-api}
      chat:
        options:
          model: qwen-plus
#          model: deepseek-v3.2

