server:
  # 端口
  port: 11503

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token前缀
  #  token-prefix: Bearer
  # jwt秘钥
  jwt-secret-key: 123456
  # cookie配置,浏览器的时候需要
  is-read-cookie: false
  is-lasting-cookie: false


spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    # password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        


user-config:
  match-path-list:
    - "/api/**"
    - "/admin/**"
    - "/dashboard/**"
    - "/user/**"
    - "/order/**"
    - "/customer/**"
    - "/warehouse/**"
    - "/sales/**"
  ## 不拦截的,比如swagger-ui等等
  not-match-path-list:
    - "/auth/*"
    - "/public/**"
    - "/api/public/**"
    - "/error"
    - "/actuator/**"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - /swagger-ui.html
    - /swagger-ui/**
    - /swagger-resources/**
    - /v2/api-docs
    - /v3/api-docs/**
    - /webjars/**
    - /doc.html
    - /favicon.ico
    - /error
