<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ax-springboot2-demo</artifactId>
        <groupId>com.github.axinger</groupId>
        <version>2026.01.01-2.7</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <artifactId>a03-websocket</artifactId>

    <modules>
        <module>a0301-javax-websocket</module>
        <module>a0302-spring-websocket</module>
        <module>a0303-spring-websocket-stomp</module>
        <module>a0304-netty-websocket</module>
        <module>a0305-netty-websocket</module>
    </modules>

</project>
