<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ax-springboot3-demo</artifactId>
        <groupId>com.github.axinger</groupId>
        <version>2026.01.01-3.5</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <artifactId>b01-springboot3-learn</artifactId>

    <properties>

    </properties>

    <modules>

        <module>b01-01-spring-boot-mvc</module>
    </modules>


    <dependencies>
        <dependency>
            <groupId>com.github.axinger</groupId>
            <artifactId>util-springboot3-starter</artifactId>
        </dependency>

    </dependencies>


    <dependencyManagement>


        <dependencies>
            <!-- a01-26-b 是 Spring Boot 2 项目中的模块，在 Spring Boot 3 项目中不存在 -->
            <!-- 如果需要使用类似功能，请在当前项目中创建对应的模块 -->
        </dependencies>
    </dependencyManagement>
</project>
