<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ax-springboot3-demo</artifactId>
        <groupId>com.github.axinger</groupId>
        <version>2026.06.01-3.5</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <artifactId>b07-springboot3-cloud-alibaba</artifactId>


    <modules>
        <module>b07-02-alibaba-dubbo</module>
        <module>b07-03-alibaba-mall-gateway</module>
        <module>b07-04-alibaba-mall-order</module>
        <module>b07-05-alibaba-mall-payment</module>
        <module>b07-06-alibaba-nacos</module>
        <module>b07-07-alibaba-nacos-gateway</module>
        <module>b07-08-alibaba-openfeign-nacos-consume</module>
        <module>b07-09-alibaba-openfeign-nacos-provider</module>
        <module>b07-10-alibaba-seata</module>
        <module>b07-11-alibaba-sentinel</module>
        <module>b07-12-alibaba-sleuth</module>
    </modules>

</project>
