<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ax-springboot3-demo</artifactId>
        <groupId>com.github.axinger</groupId>
        <version>2026.01.01-3.5</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <artifactId>b07-springboot3-cloud-alibaba</artifactId>


    <modules>
        <module>a07-springboot3-cloud-alibaba-dubbo</module>
        <module>a07-springboot3-cloud-alibaba-sentinel</module>
        <module>a07-springboot3-cloud-alibaba-seata</module>
        <module>a07-springboot3-cloud-alibaba-nacos-demo</module>
        <module>a07-springboot3-cloud-alibaba-nacos-gateway</module>
        <module>a07-springboot3-cloud-alibaba-openfeign-nacos-consume</module>
        <module>a07-springboot3-cloud-alibaba-openfeign-nacos-provider</module>
        <module>a07-springboot3-cloud-alibaba-sleuth</module>
        <module>a07-springboot3-cloud-alibaba-mall-gateway-app</module>
        <module>a07-springboot3-cloud-alibaba-mall-order-app</module>
        <module>a07-springboot3-cloud-alibaba-mall-payment-app</module>
    </modules>

</project>
