<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.github.axinger</groupId>
        <artifactId>ax-enterprise-parent</artifactId>
        <version>1.0.0</version>
        <relativePath>../ax-enterprise-parent/pom.xml</relativePath>
    </parent>

    <artifactId>ax-enterprise-common</artifactId>
    <packaging>pom</packaging>
    <name>ax-enterprise-common 公共模块聚合</name>
    <description>聚合所有公共工具模块</description>

    <modules>
        <module>common-core</module>
    </modules>

</project>
