<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!--再进入里面的    <artifactId>spring-boot-dependencies</artifactId>
    比如:查看mysql版本号, 重写版本号就可以了-->

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
    </parent>

    <groupId>com.github.axinger</groupId>
    <artifactId>ax-springboot4-demo</artifactId>
    <!--年-月-第几个版本-springboot版本-->
    <version>2026.06.01-4.0</version>
    <name>ax-springboot4-demo-${project.version}</name>
    <description>个人代码总结</description>
    <packaging>pom</packaging>


    <!--统一管理jar包版本-->
    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <repackage.skip>false</repackage.skip>
        <axinger.version>${project.version}</axinger.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot-admin.version>3.0.0</spring-boot-admin.version>
        <spring-cloud.version>2023.0.3</spring-cloud.version>
        <spring-cloud-alibaba.version>2023.0.3.2</spring-cloud-alibaba.version>
        <mybatis-starter.version>2.3.2</mybatis-starter.version>
        <mybatis-plus.version>3.5.6</mybatis-plus.version>
        <mybatis-plus3.version>3.5.10.1</mybatis-plus3.version>
        <guava.version>33.3.0-jre</guava.version>
        <hutool.version>5.8.32</hutool.version>
        <fastjson2.version>2.0.49</fastjson2.version>
        <lombok.version>1.18.38</lombok.version>
        <druid.version>1.2.22</druid.version>
        <netty-all.version>4.1.118.Final</netty-all.version>
        <redisson.version>3.36.0</redisson.version>
        <minio.version>8.5.9</minio.version>
        <poi-version>5.4.0</poi-version>
        <itextpdf.version>5.5.13.3</itextpdf.version>
    </properties>

    <!--指定运行环境,每次切换需要更新一下maven,有缓存-->
    <profiles>
        <profile>
            <id>my-dev</id>
            <properties>
                <my-env>dev</my-env>
            </properties>
        </profile>
        <profile>
            <id>my-prd</id>
            <properties>
                <my-env>prd</my-env>
            </properties>
            <!--默认变量-->
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>my-test</id>
            <properties>
                <my-env>test</my-env>
            </properties>
        </profile>
    </profiles>


    <modules>
        <module>c01-spring-boot-learn</module>
        <module>c22-springboot4-grpc</module>
                <module>c22-grpc</module>
    </modules>

    <dependencies>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>
    
</project>
