server:
  servlet:
    context-path: /
  port: 10601

spring:
  main:
    web-application-type: reactive
  application:
    name: mall-gateway-app #网关作
  redis:
    host: localhost
    port: 6379
    database: 1
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5
        max-wait: 2000ms
  cloud:
    #网关
    gateway: #routes:#路由配置:参数为一个List
      # 全局CORS配置
      #      globalcors:
      #        cors-configurations:
      #          '[/**]':
      #            allowed-origin-patterns: "*"
      #            allowed-methods: "*"
      #            allowed-headers: "*"
      #            allow-credentials: true
      # 默认过滤器配置
      default-filters:
        #        # 全局限流配置
        - name: RequestRateLimiter
          args:
            #                key-resolver: "#{@ipKeyResolver}"
            #                key-resolver: "#{@pathKeyResolver}"
            key-resolver: "#{@ipAndPathKeyResolver}"
            # 每秒补充的令牌数（稳定速率）
            redis-rate-limiter.replenishRate: 1
            #令牌桶容量（最大突发流量）
            redis-rate-limiter.burstCapacity: 1
            # 👇 关键配置：每个请求消耗 1 个令牌 👇
            redis-rate-limiter.requestedTokens: 1
      #        # 重试配置
      #        - name: Retry
      #          args:
      #            retries: 3
      #            statuses: BAD_GATEWAY
      routes:
        - id: payment_rout_1 #唯一标识
          
          predicates:
            - Path=/payment/** #判断匹配条件,即地址带有/ribbon/**的请求,会转发至lb:RIBBON-CONSUMER
          filters:
            - name: RequestRateLimiter
              args:
                #                key-resolver: "#{@ipKeyResolver}"
                #                key-resolver: "#{@pathKeyResolver}"
                key-resolver: "#{@ipAndPathKeyResolver}"
                # 每秒补充的令牌数（稳定速率）
                redis-rate-limiter.replenishRate: 1
                #令牌桶容量（最大突发流量）
                redis-rate-limiter.burstCapacity: 5
                # 👇 关键配置：每个请求消耗 5 个令牌 👇
                redis-rate-limiter.requestedTokens: 5
          uri: http://localhost:10603/ #转发的地址,写服务名称
          #          uri: lb://cloud-service-payment #转发的地址,写服务名称
          order: 0
logging:
  level:
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG
