<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.github.axinger</groupId>
        <artifactId>b10-springboot3-mq</artifactId>
        <version>2026.01.01-3.5</version>
    </parent>

    <artifactId>b10-03-rocketmq</artifactId>
    <packaging>pom</packaging>


    <modules>
        <module>b10-0301-rocketmq-demo</module>
        <module>b10-0302-rocketmq-demo</module>
        <module>b10-0303-rocketmq-stream</module>
    </modules>
</project>
