<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ax-springboot2-demo</artifactId>
        <groupId>com.github.axinger</groupId>
        <version>2026.06.01-2.7</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <packaging>pom</packaging>
    <artifactId>a06-spring-cloud</artifactId>

    <modules>
        <module>consul-order</module>
        <module>consul-payment</module>
        <module>A0601-gateway-9527</module>
        <module>A0602-getaway-order</module>
        <module>A0603-getaway-payment</module>
        <module>mq-stream-api</module>
        <module>A0611-spring-cloud-config-server</module>
        <module>A0612-spring-cloud-client</module>
        <module>A0604-all-in-one</module>
    </modules>

    <dependencies>

        <dependency>
            <groupId>com.github.axinger</groupId>
            <artifactId>doc-config-spring-boot-starter</artifactId>
        </dependency>

    </dependencies>

    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>com.github.axinger</groupId>
                <artifactId>mq-stream-api</artifactId>
                <version>${axinger.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.axinger</groupId>
                <artifactId>A0602-getaway-order</artifactId>
                <version>${axinger.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.axinger</groupId>
                <artifactId>A0603-getaway-payment</artifactId>
                <version>${axinger.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
