server:
  port: 24209
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8

spring:
  data:
    redis:
      host: localhost
      port: 16380
      password: 123456
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index-name: ax-index09
        prefix: 'ax-index09:'
    dashscope:
      #      base-url: https://dashscope.aliyuncs.com/api/v1
      #      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${aliQwen-api}
      chat:
        options:
          model: qwen-plus
      # 推理模型
      embedding:
        options:
          model: text-embedding-v3

